apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-cd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision:  1.8.1
    helm:
      releaseName: longhorn

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
