apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buisness-app
  namespace: argo-cd
  labels:
    use-case: app-of-apps
spec:
  project: default

  source:
    repoURL: https://github.com/mombe090/blog-source-code.git
    targetRevision: argo-pihole-extd-certmanager
    path: src/argocd/apps/overlays/lab

  destination:
    namespace: buisness-apps
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true