apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argo-cd
  labels:
    use-case: app-of-apps
spec:
  project: default

  source:
    repoURL: https://github.com/mombe090/blog-source-code.git
    targetRevision: argo-pihole-extd-certmanager
    path: src/argocd/infra/overlays/lab

  destination:
    namespace: infra-apps
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
