apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-acme-issuer
spec:
  acme:
    email: yayamombeya090@gmail.com

    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: cloudflare-acme-issuer-tls-key

    solvers:
      - dns01:
          cloudflare:
            email: yayamombeya090@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token #reference du secret kubernetes creer auparavent
              key: token
        selector:
          dnsZones:
            - 'mombesoft.com'
