apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argo-cd
spec:
  destination:
    namespace: pihole-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision:  2.27.0
    helm:
      valuesObject:
        #Je désactive le persistant volume claim pour le DNS, car sur ce cluster on a pas encore de persistance
        #nous utiliserons dans un autre article [longhorn](https://longhorn.io)
        persistentVolumeClaim:
          enabled: false
        
        #J'utilise la fonctionnalité de metallb pour par le même ip pour les service DNS et Web de pihole
        serviceWeb:
          loadBalancerIP: 192.168.10.138
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        
        serviceDns:
          loadBalancerIP: 192.168.10.138
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        
        #J'utilise un secret existant sur le namespace pour le mot de passe admin
        #le secret a été créé avec la commande suivante:
        #kubectl create secret generic pihole-admin-password-secret --from-literal=pihole_password='my_password' -n pihole-system
        admin:
          enabled: true
          existingSecret: pihole-admin-password-secret
          passwordKey: "pihole_password"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true