name: Tflint CI
on:
  push:
    branches:
      - main
      - add-actions
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: pre-commit/action@v3.0.1
